### ISSUE TITLE
Cool project!!

### ISSUE THREAD

**Issue by arturohernandez10** [kajMork/Brick_Feeder#1]
I am researching on how to build and control a robot arm. And this code will be a great reference. 

Do you have a blog post or similar about this project? My first idea for the robot arm is a lego brick sorter.

**Comment by kajMork** [comment]
Hi.
The code is for a drum feeder that can dispense a specified amount of 2x4 LEGO bricks.
I did not make the physical construction of it, another group at my University did. 
I only wrote new firmware for it, so that it can interact with a ROS network.
This repo is the only public information i have about the project.
Is there any specific information that you need (construction of the drum feeder, electrical design, or just more documentation of the code)?
![Brick_feeder](https://user-images.githubusercontent.com/56407295/173427435-1ee94131-9166-4f3e-a927-d5bd5fe2e333.jpg)
